config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy

  validates :username, 
    presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { minimum: 3, maximum: 25 }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
    presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { maximum: 105 },
    format: { with: EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user    
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "A user must be logged in for this action"
      redirect_to signup_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show

  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new()
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article successfully created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update 
    if @article.update(article_params)
      flash[:notice] = "Article Updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private 
  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if (current_user != @article.user && !current_user.admin?)
      flash[:alert] = "You can only edit / delete your own articles"
      redirect_to articles_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Successful Log In"
      redirect_to user
    else
      flash.now[:alert] = "Invalid username/password combination"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to AlphaBlog #{@user.username}, you've created a new account!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Account Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index 
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    username = @user.username
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:alert] = "#{username} and all of their articles have been deleted."
    redirect_to root_path
  end

  private 

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if (current_user != @user && !current_user.admin?)
      flash[:alert] = "You can only edit / delete your own profile"
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravitar_for(user, options = { size: 80 })
    size = options[:size]
    hash = Digest::MD5.hexdigest(user.email)
    url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(url, alt: user.email, class: "rounded mx-auto d-block shadow mt-3")
  end
  
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-sm mb-5 bg-body rounded">
          <div class="card-header fst-italic">
            by <%= link_to article.user.username, user_path(article.user) %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 40) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-primary text-white" %>
            <% if logged_in? %>
              <% if (article.user_id == session[:user_id] || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-success text-white" %>
                <%= link_to "Delete", article_path(article), class: "btn btn-danger text-white", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Create <%= time_ago_in_words(article.created_at) %> ago, 
              edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow-sm mb-5 bg-body rounded p-5", id: "create-edit-form", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "form-label col-2"%>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of Article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 form-label"%>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of Article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-primary text-white" %>
        </div>
      <%end%>
    </div>
  </div> 
  <div class="row justify-content-center mb-3">
    <%= link_to 'Back', articles_path, class: "btn btn-success text-white"%>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>
<div class="pagination-wrapper" >
  <div class="digg_pagination">
    <%= will_paginate @articles, class: "text-center" %>
  </div>
</div>
<%= render 'article' %>
<div class="pagination-wrapper">
  <div class="digg_pagination mb-3">
    <%= will_paginate @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%=@article.title%></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow-sm mb-5 bg-body rounded">
        <div class="card-header fst-italic">
          by <%= link_to @article.user.username, user_path(@article.user) %>
          <%= link_to gravitar_for(@article.user), user_path(@article.user)%>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
           <% if logged_in? %>
              <% if (@article.user_id == session[:user_id] || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary text-white" %>
                <%= link_to "Delete", article_path(@article), class: "btn btn-danger text-white", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            <% end %>
          </div>
        <div class="card-footer text-muted">
          <small>Create <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
          <div class="row justify-content-center mb-3 mt-3">
            <%= link_to 'Back', articles_path, class: "btn btn-success text-white"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small class="text-white">Contact the developer at <%= mail_to "andrewflagstead@gmail.com", "andrewflagstead@gmail.com", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if name == "alert" %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% else %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHABLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Log Out', logout_path, class: "dropdown-item", method: :delete %>
            <%= link_to 'Delete Profile', user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure? This will also delete your articles!" } %>
          </div>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<%= link_to 'Articles', articles_path %> |
<%= link_to 'Home', root_path%>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="bg-light p-5 rounded-lg m-3 text-center text-white" id="home-jumbotron">
    <h1 class="display-4">Welcome to AlphaBlog!</h1>
    <p class="lead">This is a simple CRUD Ruby on Rails website, using Bootstrap for styling.</p>
    <hr class="my-4">
    <p>You can create a profile, create articles, view other users, and browse articles.</p>
    <% if logged_in? %>
      <%= link_to "View Articles", articles_path, class: "btn btn-primary btn-lg text-white" %>
    <% else %>
      <%= link_to "Sign Up!", signup_path, class: "btn btn-primary btn-lg text-white" %>
    <% end %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevent the creation of <%= obj.class.name.downcase %> </h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow-sm mb-5 bg-body rounded p-5", id: "create-edit-form", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "form-label col-2"%>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 form-label"%>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Email" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 form-label"%>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ?  "Sign Up!" : "Update", class: "btn btn-primary text-white") %>
        </div>
      <%end%>
    </div>
  </div> 
  <div class="row justify-content-center mb-3">
    <%= link_to 'Back', users_path, class: "btn btn-success text-white"%>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit Account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">AlphaBlog Users</h1>
<div class="pagination-wrapper" >
  <div class="digg_pagination">
    <%= will_paginate @users, class: "text-center" %>
  </div>
</div>
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-sm mb-5 bg-body rounded">
          <div class="card-header fst-italic">
           <%= link_to user.username, user_path(user) %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravitar_for(user, size: 100), user_path(user) %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View Profile", user_path(user), class: "btn btn-primary text-white" %>
            <% if logged_in?%>
              <% if user.id == session[:user_id] %>
                <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-success text-white" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete User", user_path(user), class: "btn btn-danger text-white", method: :delete,
                        data: { confirm: "Are you sure? This will delete the user and their articles!" } %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="pagination-wrapper">
  <div class="digg_pagination mb-3">
    <%= will_paginate @articles %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for AlphaBlog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<%= gravitar_for @user, size: 220 %>

<% if @user.id == session[:user_id] %>
  <div class="text-center mt-4">
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary text-white " %>
  </div>
<% end %>

<h3 class="text-center mt-4"><%= @user.username %>'s articles</h3>
<div class="pagination-wrapper" >
  <div class="digg_pagination mt-4">
    <%= will_paginate @articles, class: "text-center" %>
  </div>
</div>
<%= render 'articles/article' %>
<div class="pagination-wrapper">
  <div class="digg_pagination mb-3">
    <%= will_paginate @articles %>
  </div>
</div>